# Generated by Django 3.1.2 on 2021-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
