# Generated by Django 3.1.2 on 2021-02-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_ordereditem_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
