# Generated by Django 2.2.6 on 2019-11-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique value for product page URl, created from name.', unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for product page URl, created from name.', unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.FileField(upload_to='')),
                ('image1', models.FileField(default='default.jpg', upload_to='')),
                ('image2', models.FileField(default='default.jpg', upload_to='')),
                ('image3', models.FileField(default='default.jpg', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(help_text='comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enninapp.Category')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
    ]
