# Generated by Django 3.1.2 on 2020-10-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
