# Generated by Django 3.1.2 on 2020-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
