# Generated by Django 3.1.2 on 2020-10-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0011_category_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
