# Generated by Django 3.0.7 on 2021-02-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0012_brand_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
    ]
