# Generated by Django 3.0.7 on 2021-02-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0013_auto_20210207_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
