# Generated by Django 3.0.7 on 2021-02-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0015_auto_20210208_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, help_text='Unique value for product page URl, created from name.', max_length=50, null=True, unique=True),
        ),
    ]
