# Generated by Django 3.0.7 on 2021-02-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enninapp', '0017_auto_20210208_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
